### ISSUE TITLE
Need to enable 'esModuleInterop' in tsconfig after upgrading to v5

### ISSUE THREAD

**Issue by dagstuan** [JedWatson/react-select#4879]
Hi, 

After upgrading to `react-select@5` I get an error from `tsc` when building unless I enable `esModuleInterop` in my own `tsconfig.json`. This should not be required.

The error seems to be in `Select.d.ts`:

```
node_modules/react-select/dist/declarations/src/Select.d.ts:1:8 - error TS1259: Module '"/.../node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

1 import React, { Component, FocusEventHandler, FormEventHandler, KeyboardEventHandler, MouseEventHandler, ReactNode, RefCallback, TouchEventHandler } from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


Found 1 error.```

**Comment by mcihadkurel** [comment]
Hi, were you able to find a solution for this?

**Comment by dagstuan** [comment]
Enabling `esModuleInterop` in my own code solves the issue. But I still dont think it should be a requirement just from installing this package.

**Comment by Methuselah96** [comment]
I was able to reproduce the issue with `esModuleInterop` and `skipLibCheck` disabled. I've opened a PR to resolve it.
