### ISSUE TITLE
Typescript error when importing "react-select/creatable" with moduleResolution "Node16" and "NodeNext"

### ISSUE THREAD

**Issue by mlandalv** [JedWatson/react-select#5474]
Error occurs in `5.6.0`. It works in `5.5.2`.

```
// From package.json
"typescript": "^4.8.4",
"react-select": "^5.6.0",
```

```
// Example.tsx
import Select from 'react-select/creatable';
```

With moduleResolution "Node16" or "NodeNext".

    Cannot find module 'react-select/creatable' or its corresponding type declarations.

Still works with moduleResolution "Node" though, which I guess is most common.

This seems to only affect creatable. `import Selectable from 'react-select'` works with Node16 and NodeNext.

**Comment by LucianoRochaDev** [comment]
Same thing here boys! Please, help us! 
Thx...

**Comment by konsalex** [comment]
Same here for `Creatable` and `AsyncSelect` cannot be imported.

A reproduction link also: https://codesandbox.io/s/react-select-next-issue-mom84i?file=/src/App.tsx with a failing import
