### ISSUE TITLE
Cannot import types after update

### ISSUE THREAD

**Issue by xec** [JedWatson/react-select#5770]
After updating to latest (5.7.7) I get an error when attempting a type (the `Select` class):

```ts
import type SelectClass from 'react-select/dist/declarations/src/Select'
```

```
Cannot find module 'react-select/dist/declarations/src/Select' or its corresponding type declarations.ts(2307)
```

The culprit seems to be the `exports` section in `package.json` which only allows very specific imports.

This was introduced in https://github.com/JedWatson/react-select/pull/5559

I've suggested a fix in https://github.com/JedWatson/react-select/pull/5769 by adding an export rule for type definitions, but I'm open to other solutions/suggestions if any :)

**Comment by xec** [comment]
Closing since I found a duplicate of this, sorry about the noise!

https://github.com/JedWatson/react-select/issues/5743
