### ISSUE TITLE
Uncaught TypeError: (0 , _classnames2.default) is not a function

### ISSUE THREAD

**Issue by dbkaplun** [JedWatson/react-select#582]
Looks to be caused by b0e2cd8.

https://github.com/JedWatson/react-select/blob/d2d642c7be118ba97b548f15e83f78f7510bc247/lib/Select.js#L532
https://github.com/JedWatson/react-select/blob/81049eeee611da3db446a1c37a3488fc6672e5cf/lib/Value.js#L71

**Comment by bogdanmarin** [comment]
Is there a fix for this? I have the same error with the multiselect example.
Uncaught TypeError: (0 , h.default) is not a function (minified version).

**Comment by ir0ny1** [comment]
Anyone ? :/ *bashes head against wall*

**Comment by sabcio** [comment]
Having the same problem

`Uncaught TypeError: (0 , _classnames2.default) is not a function`

I'm using b2afb88 and I have no idea for a workaround.

**Comment by tomprats** [comment]
Any luck anyone?

**Comment by tomprats** [comment]
For anyone else who stumbles upon this. The problem was with using files from `dist/` without also including the dependencies (`classnames` and `input-autosize`)

**Comment by theaqua** [comment]
It's because Babel 6 changed behavior of exports.

`redux-logger` has [same problem](https://github.com/fcomb/redux-logger/issues/98), it fixed by [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports).

**Comment by awe2m2n2s** [comment]
@tomprats workaround worked for me! thanks!

**Comment by Ahad-Wasim** [comment]
I encountered the same issue. Later I figured out that I did not wrap the _bindActionCreators_ method in curly braces!

`import { bindActionCreators } from "redux";`

**Comment by qodesmith** [comment]
In my case, it was forgetting to wrap _connect_ in curlys:

`import { connect } from 'react-redux'`

**Comment by Unique111** [comment]
I still don't know how to fix the problem, can help ?

**Comment by qodesmith** [comment]
@Unique111 Have you looked through your code to make sure you have the correct variables wrapped in curly's? That was the culprit for me and some others on this thread.

**Comment by Unique111** [comment]
I think the culprit for me is not the curlys，because I didn't use react-redux @qodesmith 
It should be "For anyone else who stumbles upon this. The problem was with using files from dist/ without also including the dependencies (classnames and input-autosize)"，so how to do with this？I am new for this~ @tomprats

**Comment by davidbasalla** [comment]
@Unique111 I had to put the following into my application.js file:

**Comment by CharlieScarver** [comment]
@Unique111 I like your question mark. U+FF1F

**Comment by agirton** [comment]
Closing this as it can be resolved by following https://github.com/JedWatson/react-select/issues/582#issuecomment-163072471 recommendation. Note this can widely depend on your setup and how you load in dependencies.

**Comment by tavurth** [comment]
Found this from Google.

In my case it was because I was importing `A.js` from `B.js`, and `B.js` from `A.js`.

**Comment by hanzlahabib** [comment]
putting curly braces arround variable worked for me 
import { capitalizeFirstLetter } from '../../utils/common/functions'
