### ISSUE TITLE
Plunker not working with any version after 1.0.0-rc.3

### ISSUE THREAD

**Issue by samuelcolvin** [JedWatson/react-select#2218]
Trying to create a plnkr example of a bug, but your plunkr example breaks with any version greater than `rc.3`.

### Steps to reproduce

Go to https://plnkr.co/edit/dHygFMWWqVwaRAfpEmbn?p=preview change the react select version to `1.0.0-rc.4` (or `1.1.0`) and look in the console for errors.

### Error

For `rc.4` the error is `Error: Cannot find module 'create-react-class'`

For more later versions the error becomes `TypeError: Cannot read property 'func' of undefined`

**Comment by fedde-s** [comment]
I think I got 1.0.0 working in the example for bug report #2169 by tweaking the other dependencies. If that is the solution for 1.1.0, the example linked from [`ISSUE_TEMPLATE.md`](https://github.com/JedWatson/react-select/blob/v1.1.0/ISSUE_TEMPLATE.md) should probably be updated to include the new dependencies.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
